name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.3.0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev

      - name: Pin ahrefs's sodium fork
        run: |
          opam pin add sodium https://github.com/ahrefs/ocaml-sodium.git -y
          opam update

      - name: Install deps
        run: |
          opam install . --deps-only --with-test -y

      - name: Build
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest

      - name: Copy binaries
        run: |
          mkdir -p dist
          cp _build/default/reznc/main.exe dist/reznc
          cp _build/default/server/main.exe dist/server
          cp _build/default/verify/main.exe dist/verify

      - name: Make binaries executable
        run: chmod +x dist/*

      - name: Install packaging dependencies
        run: sudo apt-get install -y ruby ruby-dev build-essential libssl-dev && sudo gem install --no-document fpm

      - name: Create .deb package
        run: |
          make ARCH=amd64 RAW_VERSION=${{ github.ref_name }}
          cp *.deb dist/

      - name: Create tarball of binaries
        run: tar -czvf dist/rezn-dsl_amd64.tar.gz -C dist reznc server verify

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.tar.gz
            dist/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
